feat: Oval OEV rewards wstETH/USDT
morpho-org/morpho-blue-reward-programs pull request #19
Opened 2024-07-30 14:40 UTC by md0x

## Context

2024-08-01 07:32 UTC, gabin54 commented
Hey @md0x! When you are ready, you can:
- Put the PR in Ready for review
- Send the funds to `0x330eefa8a787552DC5cAd3C3cA644844B1E61Ddb` using `0x9Cc5b1bc0E1970D44B5Adc7ba51d76a5DD375434`
When this will be done, we will be able to merge the PR.

2024-08-08 08:55 UTC, yum0e requested changes

2024-08-08 08:55 UTC, yum0e commented on src/market-programs.ts
> +      supply: 623424419249185042,
We also need the big endian here @md0x please, alongside the update of the start date. 
```suggestion
      supply: 623424419249185042n,
```

2024-08-09 07:08 UTC, gabin54 approved these changes

2024-08-09 07:09 UTC, yum0e approved these changes

2024-08-09 07:11 UTC, merged