feat: Oval OEV rewards pufETH/USDC
morpho-org/morpho-blue-reward-programs pull request #20
Opened 2024-07-30 14:46 UTC by md0x

## Context

2024-08-08 08:52 UTC, yum0e requested changes

2024-08-08 08:52 UTC, yum0e commented on src/market-programs.ts
> +      supply: 94597806657332024,
Can you add a big endian notation here as well please? 
```suggestion
      supply: 94597806657332024n,
```

2024-08-09 07:07 UTC, yum0e approved these changes

2024-08-09 07:08 UTC, gabin54 approved these changes

2024-08-09 07:24 UTC, merged